[build]
    base = "."
    publish = "./build"
    command = "yarn build"
[[redirects]]
    from = "https://mbhsml.netlify.app/*"
    to = "https://ml.mbhs.edu/:splat"
    status = 301
    force = true
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
    force = false